services:

  bot:
    restart: always
    volumes:
      - ./tmp:/bot/tmp
      - ./data:/bot/data
    build:
      context: .
      dockerfile: Dockerfile
    command: python bot.py

  web:
    restart: always
    ports:
      - "80:8000"
    volumes:
      - ./tmp:/bot/tmp
      - ./data:/bot/data
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn web.main:app --host 0.0.0.0 --port 8000
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN:-changeme}
